# Generated by Django 4.2 on 2023-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('I', 'Initializado'), ('F', 'Finalizado')], default='I', max_length=1),
        ),
    ]
